### ISSUE TITLE
Recognize YouTube TV URLs

### ISSUE THREAD

**Issue by da2x** [flattr/flattr-extension#58]
YouTube TV interface URLs aren’t recognized and don’t get attributed to the creator properly.

Here are some example URLs:

https://www.youtube.com/tv#/watch/video/control?v=YA-Enxfhl0E
https://www.youtube.com/tv#/watch/video/idle?v=YA-Enxfhl0E&resume
https://www.youtube.com/tv#/watch/video/seek?v=YA-Enxfhl0E&resume

**Comment by ThomasGreiner** [comment]
I see the problem. We're currently [stripping away](https://github.com/flattr/flattr-extension/blob/499b9e06fbda02572aadc3d1a72133ab49d30525/src/lib/common/utils.js#L66) the fragment from the URL together with various other information that may contain personal data such as user IDs. On top of that, I'm not sure whether our backend is capable of determining which author the flattr should be attributed so I'd have to check with the flattr.com devs on that.

In general I wouldn't expect many people to be aware of even use those URLs in a supported browser. I'd imagine Firefox on Fire TV and other TV platforms would be a great target platform but AFAIK it doesn't support Firefox extensions because it's using the Firefox Focus codebase.

**Comment by da2x** [comment]
What does your logs say on the number of submissions of `https://www.youtube.com/tv`?

That page in a regular browser tab running in fullscreen in a regular web browser is a favorite among /r/htpc users on Reddit. My Chromecast recently died so I went from submitting nothing from YouTube to a couple hundred submissions a month from my replacement HTPC.

**Comment by ThomasGreiner** [comment]
I've checked back regarding its significance and  the server team is working on improving support for it. Therefore it seems reasonable to go forward with this request now so thanks for the pull request.

**Comment by da2x** [comment]
YouTube has discontinued its TV interface.
